version: '3'
 
services:
  automatica:
    build:
      context:  ../
      dockerfile: docker/automatica/Dockerfile
    ports:
      - "5001:5001"
      - "1883:1883"
      - "5000:5000"
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - automatica
      
      
      