version: '3'
 
services:
  automatica:
    image: automaticacore/automatica-demo:develop-latest
    ports:
      - "5001:5001"
 
  nginx:
    image: automaticacore/automaticacore_proxy:develop-latest
    restart: always
    ports:
      - "80:80"
    links:
      - automatica
      
      
      